apiVersion: 1

# see http://docs.grafana.org/administration/provisioning/
datasources:
- name: graphite
  type: graphite
  access: proxy
  url: http://graphite/
  isDefault: false
  editable: true
  jsonData:
    graphiteVersion: "1.1"
- name: prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: false
  editable: true
- name: influxdb-express4
  type: influxdb
  access: proxy
  url: http://influx:8086
  isDefault: false
  editable: true
  database: express4
  user: admin
  password: admin
- name: elasticsearch-express4
  type: elasticsearch
  access: proxy
  isDefault: false
  editable: true
  database: "[metric-express4-]YYYY-MM-DD"
  url: http://elasticsearch:9200
  jsonData:
    interval: Daily
    timeField: "timestamp"
