version: "3"

services:

  node6:
    build:
      context: ./test
      dockerfile: Dockerfile-node6
    user: "node"
    entrypoint: "/opt/inspector-csv/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-csv/
    working_dir: "/opt/inspector-csv"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-csv/.tmp/.npm/"
      - NODE_VERSION=6

  node7:
    build:
      context: ./test
      dockerfile: Dockerfile-node7
    user: "node"
    entrypoint: "/opt/inspector-csv/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-csv/
    working_dir: "/opt/inspector-csv"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-csv/.tmp/.npm/"
      - NODE_VERSION=7

  node8:
    build:
      context: ./test
      dockerfile: Dockerfile-node8
    user: "node"
    entrypoint: "/opt/inspector-csv/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-csv/
    working_dir: "/opt/inspector-csv"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-csv/.tmp/.npm/"
      - NODE_VERSION=8

  node9:
    build:
      context: ./test
      dockerfile: Dockerfile-node9
    user: "node"
    entrypoint: "/opt/inspector-csv/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-csv/
    working_dir: "/opt/inspector-csv"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-csv/.tmp/.npm/"
      - NODE_VERSION=9

  node10:
    build:
      context: ./test
      dockerfile: Dockerfile-node10
    user: "node"
    entrypoint: "/opt/inspector-csv/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-csv/
    working_dir: "/opt/inspector-csv"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-csv/.tmp/.npm/"
      - NODE_VERSION=10
